AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${AWS::StackName}-bucket
    Metadata:
      SamResourceId: S3Bucket
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
    Metadata:
      SamResourceId: LambdaExecutionRole
  LambdaExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3AccessPolicy
      Roles:
      - Ref: LambdaExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:PutObject
          - s3:ListBucket
          Resource:
          - Fn::Sub: arn:aws:s3:::${S3Bucket}
          - Fn::Sub: arn:aws:s3:::${S3Bucket}/*
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource: arn:aws:logs:*:*:*
    Metadata:
      SamResourceId: LambdaExecutionPolicy
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-MyLambdaFunction
      Handler: lambda_handler.lambda_handler
      Runtime: python3.12
      CodeUri: s3://s3-lambda-invoke-sample/537d22b691b25653bea9453921e95040
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Layers:
      - arn:aws:lambda:us-east-1:297552353691:layer:s3-lambda-layer:1
      Events:
        S3UploadEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: S3Bucket
            Events:
            - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .xlsx
    Metadata:
      SamResourceId: MyLambdaFunction
  FastApiLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fastapi-lambda
      Handler: main.handler
      Runtime: python3.12
      CodeUri: s3://s3-lambda-invoke-sample/466095479ddb6ffef55e48d7cbb837ae
      MemorySize: 128
      Timeout: 10
      Layers:
      - arn:aws:lambda:us-east-1:297552353691:layer:s3-lambda-layer:1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
    Metadata:
      SamResourceId: FastApiLambdaFunction
Outputs:
  S3BucketName:
    Value:
      Ref: S3Bucket
  LambdaFunctionName:
    Value:
      Fn::GetAtt:
      - MyLambdaFunction
      - Arn
